"""
Memory Domain Models

Defines the core data structures for the provider-agnostic memory subsystem.

Architecture Layer: Core / Models
"""

import uuid
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field


class MemoryRecordType(str, Enum):
    """Broad categories of memory."""

    WORKING = "working"  # Ephemeral context for current execution
    LONG_TERM = "long_term"  # Persistent factual knowledge
    REFLECTION = "reflection"  # Supervisor reflections, feedback, self-evaluations
    KNOWLEDGE = "knowledge"  # External documents, project details
    EXECUTION = "execution"  # Execution summaries, traces, logs


class MemorySource(str, Enum):
    """The origin of a memory record."""

    SYSTEM = "system"  # Generated by core systems (e.g., orchestrator, tools)
    AGENT = "agent"  # Generated by a specific agent
    USER = "user"  # Provided directly by user
    REFLECTION = "reflection"  # Generated by the Reflection engine
    EXTERNAL = "external"  # Imported from external APIs or databases


class MemoryPolicy(BaseModel):
    """Defines lifecycle rules for memory records."""

    ttl_seconds: Optional[int] = None
    is_ephemeral: bool = False
    priority: int = 1


class MemoryMetadata(BaseModel):
    """Structured metadata attached to a memory record for fast filtering."""

    source: MemorySource = MemorySource.SYSTEM
    policy: MemoryPolicy = Field(default_factory=MemoryPolicy)
    tags: List[str] = Field(default_factory=list)
    attributes: Dict[str, Any] = Field(default_factory=dict)

    # Pre-defined optional indices
    goal_id: Optional[str] = None
    task_id: Optional[str] = None
    agent_id: Optional[str] = None


class MemoryRecord(BaseModel):
    """The foundational unit of stored information."""

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    record_type: MemoryRecordType
    content: str
    metadata: MemoryMetadata = Field(default_factory=MemoryMetadata)
    timestamp: datetime = Field(default_factory=datetime.utcnow)

    # The vectorized representation (if applicable)
    embedding: Optional[List[float]] = None


class MemoryQuery(BaseModel):
    """Structured query for memory retrieval."""

    text: Optional[str] = None
    record_types: Optional[List[MemoryRecordType]] = None
    tags: Optional[List[str]] = None
    attributes: Optional[Dict[str, Any]] = None
    top_k: int = 5

    # Specific filters
    goal_id: Optional[str] = None
    task_id: Optional[str] = None
    agent_id: Optional[str] = None


class MemoryResult(BaseModel):
    """A retrieved memory record with matching details."""

    record: MemoryRecord
    relevance_score: float
    # Explanability fields
    matched_fields: List[str] = Field(default_factory=list)
    match_reason: Optional[str] = None


class MemoryCollection(BaseModel):
    """Logical grouping of memory records."""

    name: str
    description: str
    record_types: List[MemoryRecordType]


class MemoryStatistics(BaseModel):
    """Aggregated statistics for a memory provider."""

    total_records: int
    records_by_type: Dict[str, int]
    storage_size_bytes: Optional[int] = None
